name = "LinkFunctions"
uuid = "fa965eab-f9a2-49de-8293-bc60088b3cbc"
authors = ["Giovanni Tinervia"]
version = "1.0.0-DEV"

[compat]
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
