name = "LinkFunctions"
uuid = "fa965eab-f9a2-49de-8293-bc60088b3cbc"
authors = ["Giovanni Tinervia"]
version = "1.0.0-DEV"

[deps]
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
LogExpFunctions = "2ab3a3ac-af41-5b50-aa03-7779005ae688"

[compat]
Distributions = "0.25.120"
LogExpFunctions = "0.2.0-0.3.29"
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
